export const STATUS_CHANNEL_SUBSCRIBE_REQUEST = `auth/STATUS_CHANNEL_SUBSCRIBE_REQUEST`;
export const STATUS_CHANNEL_SUBSCRIBE_SUCCESS = `auth/STATUS_CHANNEL_SUBSCRIBE_SUCCESS`;
export const STATUS_CHANNEL_SUBSCRIBE_FAILURE = `auth/STATUS_CHANNEL_SUBSCRIBE_FAILURE`;

export const STATUS_CHANNEL_UNSUBSCRIBE_REQUEST = `auth/STATUS_CHANNEL_UNSUBSCRIBE_REQUEST`;
export const STATUS_CHANNEL_UNSUBSCRIBE_SUCCESS = `auth/STATUS_CHANNEL_UNSUBSCRIBE_SUCCESS`;
export const STATUS_CHANNEL_UNSUBSCRIBE_FAILURE = `auth/STATUS_CHANNEL_UNSUBSCRIBE_FAILURE`;

export const STATUS_UPDATE = `auth/STATUS_UPDATE`;

export const SIGN_UP_REQUEST = `auth/SIGN_UP_REQUEST`;
export const SIGN_UP_SUCCESS = `auth/SIGN_UP_SUCCESS`;
export const SIGN_UP_FAILURE = `auth/SIGN_UP_FAILURE`;

export const SIGN_IN_POPUP_REQUEST = `auth/SIGN_IN_POPUP_REQUEST`;
export const SIGN_IN_POPUP_SUCCESS = `auth/SIGN_IN_POPUP_SUCCESS`;
export const SIGN_IN_POPUP_FAILURE = `auth/SIGN_IN_POPUP_FAILURE`;

export const SIGN_IN_REQUEST = `auth/SIGN_IN_REQUEST`;
export const SIGN_IN_SUCCESS = `auth/SIGN_IN_SUCCESS`;
export const SIGN_IN_FAILURE = `auth/SIGN_IN_FAILURE`;

export const SIGN_OUT_REQUEST = `auth/SIGN_OUT_REQUEST`;
export const SIGN_OUT_SUCCESS = `auth/SIGN_OUT_SUCCESS`;
export const SIGN_OUT_FAILURE = `auth/SIGN_OUT_FAILURE`;
